export const ABOUT_JSON_PATH = '/data/about.json'
export const EDUCATION_JSON_PATH = '/data/education.json'
export const WORKS_JSON_PATH = '/data/work.json'
export const HOME_JSON_PATH = '/data/home.json'
export const DEV_JSON_PATH = '/data/dev.json'
